version: "3.9"
services:
  web:
    image: myapp:latest
    build: .
    container_name: macoui_admin_container
    restart: unless-stopped
    ports:
      - "3020:3000"   # host:container
    environment:
      NODE_ENV: development
    volumes:
      - /var/www/myapp/.next:/app/.next # اختیاری
