version: "3.9"
services:
  web:
    image: myapp:latest
    build: .
    container_name: macoui_admin_container
    restart: always
    ports:
      - "3020:3020"
    environment:
      NODE_ENV: production
    volumes:
      - /var/www/myapp/.next:/app/.next # اختیاری: برای debug / cache
